[package]
authors = ["wanzulfikri"]
edition = "2018"
name = "ssg_lib"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
pulldown-cmark = "0.8"
